### PR TITLE
Update catalog-info-1.yaml

### PR DESCRIPTION
**Pull request by punkle**

### CODE REVIEW

**Review by dtuite — APPROVED** [review]

**Comment by dtuite** [comment]
@punkle I was able to successfully import `catalog-info-1.yaml` into Roadie on Roadie without this change in place and TechDocs worked fine. Could you describe what the problem is that this commit fixes please?

**Review by iain-b — APPROVED** [review]

**Comment by punkle** [comment]
@dtuite @iain-b I didnt get a chance to revisit this. @dtuite you gave me cause for doubt that this is the correct fix. Maybe it is though?

**Comment by punkle** [comment]
I will look into it later today if I get a chance.

**Comment by dtuite** [comment]
@punkle I chatted to iain and my doubt is now gone. Merge away IMO.

**Pull request merged**
